version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region eu-north-1 | docker login --username AWS --password-stdin 691580494714.dkr.ecr.eu-north-1.amazonaws.com
  build:
    commands:
      - docker build -t bank-prediction .
      - docker tag bank-prediction:latest 691580494714.dkr.ecr.eu-north-1.amazonaws.com/bank-prediction:latest
  post_build:
    commands:
      - docker push 691580494714.dkr.ecr.eu-north-1.amazonaws.com/bank-prediction:latest
      - echo Writing image definitions file...
      - printf '[{"name":"bank-prediction","imageUri":"%s"}]' 691580494714.dkr.ecr.eu-north-1.amazonaws.com/bank-prediction:latest > imagedefinitions.json

artifacts:
  files:
    - imagedefinitions.json

